# Auto-generated by run_spirl_with_d4rl.sh
pu_defaults = dict(
    # Keep expert_root=None so train.py defaults to the original conf.general.data_dir (SPiRL expert).
    expert_root = None,
    # Use the converted D4RL folder as "general" data root:
    general_root = r'/mnt/e/WSL/Linux/spirl/spirl/data_d4rl_general/kitchen/kitchen-mixed-v0',

    # PU / discriminator hyperparams (tune via environment variables if you like)
    pu_lambda = 0.6,
    pu_xi     = 0.0,
    pu_weight = 1.0,
    disc_hidden = (256, 256),

    # SDE regularization on the prior
    sde_sigma_prior = 0.01,
    sde_alpha       = 1.0,
)
