# Auto-generated by run_spirl_with_d4rl.sh
pu_defaults = dict(
    expert_root = None,                 # fallback to conf.general.data_dir (SPiRL expert)
    general_root = r'/mnt/e/WSL/Linux/spirl/spirl/data_d4rl_general/maze/maze2d-medium-sparse-v1',   # converted D4RL folder (or None)

    pu_lambda = 0.6,
    pu_xi     = 0.0,
    pu_weight = 1.0,
    disc_hidden = (256, 256),

    sde_sigma_prior = 0.01,
    sde_alpha       = 1.0,
)
